version: '3'

services:
  api-reservation:
    build: ./djBackPlaylist
    ports:
      - "3001:3001"
    command: npm start
    networks:
      - dj-marcel

networks:
  dj-marcel:
    driver: bridge
