version: '3'

services:
  api-reservation:
    build: ./djBackReservation
    ports:
      - "3002:3002"
    command: npm start
    networks:
      - dj-marcel

networks:
  dj-marcel:
    driver: bridge
