name: Deploy Rhayonne MArcel DJ
on:
  push:
    branches:
      - rCi

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull and deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 34.155.168.225
          username: maalsi
          key: ${{ secrets.KEYSERVER }}
          script: |
           cd /home/maalsi/dj-marcel
           docker-compose down
           docker-compose pull
           docker-compose up -d
